In [140]:
import pandas as pd
import numpy as np

In [142]:
data = pd.read_csv('Crop_recommendation.csv')
data.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [144]:
data.tail()

        N   P   K  temperature   humidity        ph    rainfall   label
2195  107  34  32    26.774637  66.413269  6.780064  177.774507  coffee
2196   99  15  27    27.417112  56.636362  6.086922  127.924610  coffee
2197  118  33  30    24.131797  67.225123  6.362608  173.322839  coffee
2198  117  32  34    26.272418  52.127394  6.758793  127.175293  coffee
2199  104  18  30    23.603016  60.396475  6.779833  140.937041  coffee

In [150]:
data.shape

(2200, 8)

In [154]:
data.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [156]:
X = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [160]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [164]:
model = RandomForestClassifier()

In [166]:
model.fit(X_train, y_train)

RandomForestClassifier()

In [172]:
y_pred = model.predict(X_test)

In [178]:
accuracy = model.score(X_test, y_test)
accuracy

0.9931818181818182

In [180]:
new_features = [[36,58,25,28.66024,59.31891,8.399136,36.9263]]
predicted_crop = model.predict(new_features)
predicted_crop

C:\Users\MURUGAVEL V\AppData\Roaming\Python\Python312\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['mothbeans'], dtype=object)

In [184]:
import pickle

with open('crop_prediction.pkl','wb') as file:
    pickle.dump(model, file)